version: 2
triggers:
  - schedule:
      cron: "0 0 * * *"
      filters:
        branches:
          only:
            - master

jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install miniconda
          command: |
            curl -s https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh
            bash miniconda.sh -b -p ${HOME}/miniconda

            export PATH=${HOME}/miniconda/bin:$PATH

            conda config --set always_yes yes --set changeps1 no
            conda config --add channels defaults
            conda config --add channels conda-forge
            conda update -q conda

            source activate base

            conda install -y -q \
              nomkl \
              conda \
              conda-build \
              pytest \
              python=3.7

      - run:
          name: conda list and info
          command: |
            export PATH=${HOME}/miniconda/bin:$PATH
            source activate base
            conda list
            echo " "
            conda info

      - run:
          name: test simple builds
          command: |
            export PATH=${HOME}/miniconda/bin:$PATH
            source activate base
            mkdir -p ${HOME}/tests
            pytest -vv -s test_simple_builds.py

      - run:
          name: test complicated builds
          command: |
            export PATH=${HOME}/miniconda/bin:$PATH
            source activate base
            mkdir -p ${HOME}/tests
            pytest -vv -s test_complicated_builds.py
