version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v0-dependencies

      - run:
          name: install dependencies
          command: |
            if [ ! -d miniconda ]; then
              curl -s https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh
              bash miniconda.sh -b -p miniconda

              export PATH=`pwd`/miniconda/bin:$PATH

              conda config --set always_yes yes --set changeps1 no
              conda config --add channels defaults
              conda config --add channels conda-forge
              conda update -q conda

              conda create -q -n test-env \
                python=3.6 \
                pip
            fi

            export PATH=`pwd`/miniconda/bin:$PATH

            conda config --set always_yes yes --set changeps1 no
            conda config --add channels defaults
            conda config --add channels conda-forge
            conda update -q conda

            source activate test-env

            conda install -y -q \
              nomkl \
              conda \
              conda-build \
              pytest

      - save_cache:
          paths:
            - ./miniconda
          key: v0-dependencies

      - run:
          name: info
          command: |
            export PATH=`pwd`/miniconda/bin:$PATH
            source activate test-env
            conda list
            echo " "
            conda info

      - run:
          name: build-base
          command: |
            export PATH=`pwd`/miniconda/bin:$PATH
            source activate test-env
            echo "building packages"

      - run:
          name: test
          command: |
            export PATH=`pwd`/miniconda/bin:$PATH
            source activate test-env
            pytest -vv test_conda.py
