version: 2
nightly:
  triggers:
    - schedule:
        cron: "0 0 * * *"
        filters:
          branches:
            only:
              - master

jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v0-dependencies

      - run:
          name: install dependencies
          command: |
            if [ ! -d "${HOME}/miniconda" ]; then
              curl -s https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh
              bash miniconda.sh -b -p ${HOME}/miniconda

              export PATH=${HOME}/miniconda/bin:$PATH

              conda config --set always_yes yes --set changeps1 no
              conda config --add channels defaults
              conda config --add channels conda-forge
              conda update -q conda
            fi

            export PATH=${HOME}/miniconda/bin:$PATH

            conda config --set always_yes yes --set changeps1 no
            conda config --add channels defaults
            conda config --add channels conda-forge
            conda update -q conda

            source activate base

            conda install -y -q \
              nomkl \
              conda \
              conda-build \
              pytest \
              python=3.7

      - save_cache:
          paths:
            - ./miniconda
          key: v0-dependencies

      - run:
          name: info
          command: |
            export PATH=${HOME}/miniconda/bin:$PATH
            source activate base
            conda list
            echo " "
            conda info

      - run:
          name: build-test-base
          command: |
            export PATH=${HOME}/miniconda/bin:$PATH
            source activate base

            mkdir -p ${HOME}/tests

            echo "building packages..."

            conda build recipes/pkg_a
            if [ ! -f "${HOME}/tests/a_tests_ran" ]; then exit 1; fi
            rm ${HOME}/tests/*
            echo " "

            conda build recipes/pkg_b
            if [ ! -f "${HOME}/tests/b_tests_ran" ]; then exit 1; fi
            rm ${HOME}/tests/*
            echo " "

            conda build --use-local recipes/pkg_c
            if [ ! -f "${HOME}/tests/c_tests_ran" ]; then exit 1; fi
            rm ${HOME}/tests/*
            echo " "

            ls -1 ${HOME}/miniconda/conda-bld/*/*

      - run:
          name: test
          command: |
            export PATH=${HOME}/miniconda/bin:$PATH
            source activate base
            pytest -vv test_conda.py
